name: "Version Control Deploy"
description: "Trigger deploy to production instance"
inputs:
  apiUrl:
    description: "Base API URL like https://prod-instance.spicaengine.com/api"
    required: true
  apiKey:
    description: "API Key for authentication"
    required: true
  remote:
    description: "Remote name like 'origin'"
    required: true
  branch:
    description: "Branch like, 'main'"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
